# @package _global_

dataset:
  view_sampler:
    min_distance_between_context_views: 10
    max_distance_between_context_views: 10
    min_distance_to_context_views: 1
    warm_up_steps: 50_000
    initial_min_distance_between_context_views: 2
    initial_max_distance_between_context_views: 2
    num_target_views: 1
